import React, { useState } from 'react';
// import BurgerPane from './components/BurgerPane'
import Ingredient from './Ingredient'
//PROPS WAY (this is grabbing the item array that was created in the parent (app.js))
// const IngredientList = (props) =>{
//     {items.map((item, index)=>{
//         console.log(item)
//         //this is now going to render the ingredient component. The key is automatically generated by using the map function.
//         // to get all the info from the item array instead of having to list everything, you can make it
//         //equal itself. That will pass the entire object.
//       
// }
const IngredientList = (props) =>{
    return (
        <div style={{border: '3px solid red', width:'30%'}}>
           {/* {props.name} {props.color} {props.itemIndex} <button>Add</button> */}
           <Ingredient items={props.items} addItem={props.addItem} />

       </div>
    )}

export default IngredientList
































// import React, { useState } from 'react';


// //import BurgerPane from "./BurgerPane";
// //import Ingredient from './Ingredient'

// //components Import
// //this is grabbing the item array that was created in the parent app.js 
// // const IngredientList = ({props}) => {
    
// //         //this is now going to render infredient component. the key is automatically is generedted using map function
// //         //get all info from the item array instead of having to list everything, you can make it 
// //         //equal itself. This will pass entire object  
// //        return(
// //            <div> {props.name} 
// //            </div>
           
// //        )}


// const IngredientList = (props) =>{
//     return (
//         <div>
//            {props.name}
//        </div>
//     )}

   
//   export default IngredientList;