import React, { useState } from 'react';
// import BurgerPane from './components/BurgerPane'
import Ingredient from './Ingredient'







const IngredientList = (props) =>{
    return (
        <div style={{border: '3px solid red', width:'30%'}}> 
            {props.name} {props.itemIndex} 
            {/* <button onClick={(e)=>{props.addItem(e, newItem)}}>add</button> */}
            <button onClick={props.addItem}>add</button>
            <Ingredient /> 
       </div>
    )}




    //PROPS WAY (this is grabbing the item array that was created in the parent (app.js))
// const IngredientList = (props) =>{
//     {items.map((item, index)=>{
//         console.log(item)
//         //this is now going to render the ingredient component. The key is automatically generated by using the map function.
//         // to get all the info from the item array instead of having to list everything, you can make it
//         //equal itself. That will pass the entire object.
//        return (
//        <div> 
//            <Ingredient key = {index} name={item.name} color={item.color} /> 
//        </div>
//     )})}
// }



//DESTRUCTURING WAY
// const IngredientList = ({items}) =>{
//     {items.map((item, index)=>{
//   return ( 
//         <div> 
//             <Ingredient key = {index} name={item.name}  /> 
//         </div>
//     )})
//     }
// }



export default IngredientList